<?php

declare(strict_types=1);

namespace justinholtweb\publishr\controllers;

use Craft;
use craft\helpers\DateTimeHelper;
use DateTime;
use DateTimeZone;
use justinholtweb\publishr\models\CalendarEvent;
use justinholtweb\publishr\Plugin;
use yii\web\Response;

/**
 * The month view.
 */
class CalendarController extends BaseController
{
    public function actionIndex(?int $year = null, ?int $month = null): Response
    {
        $this->requireView();

        $plugin = $this->plugin();
        $settings = $plugin->getSettings();
        $siteId = $this->siteId();

        $tz = new DateTimeZone(Craft::$app->getTimeZone());
        $now = new DateTime('now', $tz);

        $year ??= (int)$this->request->getParam('year', $now->format('Y'));
        $month ??= (int)$this->request->getParam('month', $now->format('n'));

        // Clamp rather than 404. A stale bookmark to month 13 should show December, not an error
        // page — the URL is generated by arrow buttons, and off-by-one is a normal thing to do.
        $month = max(1, min(12, $month));
        $year = max(1970, min(2200, $year));

        $lanes = $this->requestedLanes($settings->defaultLanes);
        $filters = $this->requestedFilters();

        $weeks = $plugin->calendar->grid($year, $month, $settings->weekStartDay, $tz);
        [$start, $end] = $plugin->calendar->gridWindow($weeks);

        return $this->renderTemplate('publishr/calendar', [
            'title' => Craft::t('publishr', 'Calendar'),
            'year' => $year,
            'month' => $month,
            'monthLabel' => (new DateTime(sprintf('%04d-%02d-01', $year, $month), $tz))->format('F Y'),
            'weeks' => $weeks,
            'days' => $plugin->calendar->events($start, $end, $siteId, $lanes, $filters),
            'lanes' => $lanes,
            'allLanes' => CalendarEvent::LANES,
            'laneLabels' => $this->laneLabels(),
            'filters' => $filters,
            'stages' => $plugin->stages->getAllStages(),
            'sections' => Craft::$app->getEntries()->getAllSections(),
            'today' => $now->format('Y-m-d'),
            'weekStartDay' => $settings->weekStartDay,
            'dayNames' => $this->dayNames($settings->weekStartDay),
            'maxPerDay' => $settings->maxPerDay,
            'prev' => $this->step($year, $month, -1),
            'next' => $this->step($year, $month, 1),
            'siteHandle' => Craft::$app->getSites()->getSiteById($siteId)?->handle,
            'siteOptions' => $this->siteOptions(),
            'canManage' => Craft::$app->getUser()->checkPermission(Plugin::PERMISSION_MANAGE),
        ]);
    }

    /**
     * Move a pip to another day.
     *
     * Which date this writes depends entirely on the lane it was dragged from, and that is the
     * whole reason the lane is part of the drag payload: dragging a piece in the "due" lane must
     * move its deadline, and dragging the same piece in the "publish" lane must move its post
     * date. A drag handler that guessed would move the wrong one about half the time.
     */
    public function actionMove(): Response
    {
        $this->requirePostRequest();
        $this->requireAcceptsJson();
        $this->requireManage();

        $elementId = (int)$this->request->getRequiredBodyParam('elementId');
        $siteId = (int)($this->request->getBodyParam('siteId') ?: $this->siteId());
        $lane = (string)$this->request->getRequiredBodyParam('lane');
        $date = (string)$this->request->getRequiredBodyParam('date');

        $tz = new DateTimeZone(Craft::$app->getTimeZone());
        $target = DateTime::createFromFormat('Y-m-d H:i:s', $date . ' 09:00:00', $tz);

        if ($target === false) {
            return $this->asFailure(Craft::t('publishr', 'That isn’t a date.'));
        }

        $plugin = $this->plugin();

        if (in_array($lane, [CalendarEvent::LANE_DUE, CalendarEvent::LANE_REVIEW], true)) {
            $item = $plugin->items->forElement($elementId, $siteId);

            if ($item === null) {
                return $this->asFailure(Craft::t('publishr', 'That isn’t being tracked.'));
            }

            if ($lane === CalendarEvent::LANE_DUE) {
                $plugin->items->setDueDate($item, $target, $this->currentUserId());
            } else {
                $this->requirePro(Craft::t('publishr', 'Freshness reviews'));
                $item->reviewDue = $target;
                $plugin->items->save($item);
            }

            return $this->asSuccess(Craft::t('publishr', 'Moved.'));
        }

        $entry = Craft::$app->getElements()->getElementById($elementId, \craft\elements\Entry::class, $siteId);

        if ($entry === null) {
            return $this->asFailure(Craft::t('publishr', 'That entry no longer exists.'));
        }

        if (!Craft::$app->getElements()->canSave($entry)) {
            return $this->asFailure(Craft::t('publishr', 'You can’t edit that entry.'));
        }

        // The existing time of day is kept. Dragging a post from Tuesday to Thursday is a
        // statement about the day, not an instruction to republish it at nine in the morning.
        $existing = $lane === CalendarEvent::LANE_PUBLISH ? $entry->postDate : $entry->expiryDate;

        if ($existing !== null) {
            $target->setTime((int)$existing->format('H'), (int)$existing->format('i'), (int)$existing->format('s'));
        }

        if ($lane === CalendarEvent::LANE_PUBLISH) {
            $entry->postDate = $target;
        } else {
            $entry->expiryDate = $target;
        }

        if (!Craft::$app->getElements()->saveElement($entry)) {
            return $this->asModelFailure($entry, Craft::t('publishr', 'Couldn’t move that entry.'), 'entry');
        }

        return $this->asSuccess(Craft::t('publishr', 'Moved.'));
    }

    /** @param string[] $default @return string[] */
    private function requestedLanes(array $default): array
    {
        $requested = $this->request->getParam('lanes');

        if ($requested === null) {
            return $default;
        }

        $lanes = is_array($requested) ? $requested : explode(',', (string)$requested);
        $lanes = array_values(array_intersect($lanes, CalendarEvent::LANES));

        // An empty selection means "show nothing", which is a legitimate thing to ask for and
        // exactly what unticking every box does. Falling back to the default here would make the
        // last box impossible to untick.
        return $lanes;
    }

    /** @return array<string, mixed> */
    private function requestedFilters(): array
    {
        $filters = [];

        $stageIds = $this->request->getParam('stageIds');

        if (!empty($stageIds)) {
            $filters['stageIds'] = array_map('intval', (array)$stageIds);
        }

        $sectionIds = $this->request->getParam('sectionIds');

        if (!empty($sectionIds)) {
            $filters['sectionIds'] = array_map('intval', (array)$sectionIds);
        }

        $assignee = $this->request->getParam('assigneeId');

        if ($assignee === 'me') {
            $assignee = $this->currentUserId();
        }

        if (!empty($assignee)) {
            $filters['assigneeId'] = (int)$assignee;
        }

        $search = trim((string)$this->request->getParam('search', ''));

        if ($search !== '') {
            $filters['search'] = $search;
        }

        return $filters;
    }

    /** @return array<string, string> */
    private function laneLabels(): array
    {
        return [
            CalendarEvent::LANE_DUE => Craft::t('publishr', 'Due'),
            CalendarEvent::LANE_PUBLISH => Craft::t('publishr', 'Publishing'),
            CalendarEvent::LANE_EXPIRE => Craft::t('publishr', 'Expiring'),
            CalendarEvent::LANE_REVIEW => Craft::t('publishr', 'Review'),
        ];
    }

    /** @return string[] Weekday names, rotated to the configured first day. */
    private function dayNames(int $weekStartDay): array
    {
        $names = [];

        // Anchored to a known Sunday rather than to "today minus its weekday", so the labels are
        // right in every month regardless of what day the request happens on.
        $anchor = new DateTime('2024-01-07');

        for ($i = 0; $i < 7; $i++) {
            $day = (clone $anchor)->modify('+' . (($weekStartDay + $i) % 7) . ' days');
            $names[] = $day->format('D');
        }

        return $names;
    }

    /** @return array{year: int, month: int} */
    private function step(int $year, int $month, int $by): array
    {
        $month += $by;

        if ($month < 1) {
            return ['year' => $year - 1, 'month' => 12];
        }

        if ($month > 12) {
            return ['year' => $year + 1, 'month' => 1];
        }

        return ['year' => $year, 'month' => $month];
    }
}
